# Generated by Django 5.0.3 on 2024-03-16 10:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shelter', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='catbreed',
            name='name',
            field=models.TextField(max_length=32, verbose_name="Breed's Name"),
        ),
        migrations.AlterField(
            model_name='dogbreed',
            name='name',
            field=models.TextField(max_length=32, verbose_name="Breed's Name"),
        ),
    ]
