# Generated by Django 5.0.3 on 2024-03-16 10:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shelter', '0003_petphoto_main'),
    ]

    operations = [
        migrations.AlterField(
            model_name='petphoto',
            name='main',
            field=models.BooleanField(default=False),
        ),
    ]
